title: HomeKit Device Compatibility Repository
description: Database of HomeKit compatible devices

# Build settings
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable : true
remote_theme: alexander-heimbuch/millidocs
strict_front_matter: true

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/

sass:
  sass_dir: _sass
  style: compressed

collections:
  homekit:
    output: true
    permalink: /:title.html

defaults:
  - scope:
      path: ""
      type: "homekit"
    values:
      layout: "homekit"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  
image_processing:
  table:
    source: assets/images/devices
    destination: assets/images/devices-table
    resize_to_limit: [~, 75]
